### ISSUE TITLE
failed to build on ubuntu 22.04 with g++-11

### ISSUE THREAD

**Issue by laoshaw** [openbmc/stdplus#3]
```
ninja -C builddir
ninja: Entering directory `builddir'
[20/42] Compiling C++ object src/libstdplus.so.0.1.p/net_addr_subnet.cpp.o
FAILED: src/libstdplus.so.0.1.p/net_addr_subnet.cpp.o 
c++ -Isrc/libstdplus.so.0.1.p -Iinclude -I../include -Iinclude-fd -I../include-fd -I../subprojects/function2/include -Isubprojects/function2/__CMake_build -I../subprojects/function2/__CMake_build -Isubprojects/function2 -I../subprojects/function2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c++20 -O0 -g -fPIC -MD -MQ src/libstdplus.so.0.1.p/net_addr_subnet.cpp.o -MF src/libstdplus.so.0.1.p/net_addr_subnet.cpp.o.d -o src/libstdplus.so.0.1.p/net_addr_subnet.cpp.o -c ../src/net/addr/subnet.cpp
In file included from ../src/net/addr/subnet.cpp:3:
../include/stdplus/net/addr/subnet.hpp:357:13: error: redefinition of ‘struct fmt::v8::formatter<Addr, CharT>’
  357 | struct fmt::formatter<Sub, CharT> : stdplus::Format<stdplus::ToStr<Sub>, CharT>
      |             ^~~~~~~~~~~~~~~~~~~~~
In file included from ../include/stdplus/net/addr/subnet.hpp:3,
                 from ../src/net/addr/subnet.cpp:3:
../include/stdplus/net/addr/ip.hpp:601:13: note: previous definition of ‘struct fmt::v8::formatter<Addr, CharT>’
  601 | struct fmt::formatter<Addr, CharT> :
      |             ^~~~~~~~~~~~~~~~~~~~~~
[29/42] Compiling C++ object src/libstdplus.so.0.1.p/fd_atomic.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by williamspatrick** [comment]
We use GCC-13 everywhere in the project.

**Comment by williamspatrick** [comment]
Are you missing ninja in that Docker container?

```
| CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```
